### ISSUE TITLE
ImportError: cannot import name 'NameCompare' from 'burdock.reader.sql.sql_base' (Circular reference issue around report.py?)

### ISSUE THREAD

**Issue by dylanw-oss** [opendifferentialprivacy/whitenoise-system#153]
I got below error from Databricks:

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-3410247141518354> in <module>
      9 #exact = reader.execute_typed(query_string)
     10 private = PrivateReader(reader, meta, 1.0)
---> 11 priv = private.execute_typed(query_string)

/databricks/python/lib/python3.7/site-packages/burdock/sql/private_reader.py in execute_typed(self, query_string)
     87         """
     88         query = self.parse_query_string(query_string)
---> 89         return self.execute_ast_typed(query)
     90 
     91     def _execute_ast(self, query, cache_exact=False):

/databricks/python/lib/python3.7/site-packages/burdock/sql/private_reader.py in execute_ast_typed(self, query)
    269             raise ValueError("Please pass ASTs to execute_typed.  To execute strings, use execute.")
    270 
--> 271         return self._execute_ast(query, False)
    272 
    273 class PrivateReaderOptions:

/databricks/python/lib/python3.7/site-packages/burdock/sql/private_reader.py in _execute_ast(self, query, cache_exact)
    235 
    236             if hasattr(out, 'sortBy'):
--> 237                 out = out.sortBy(sort_func)
    238             else:
    239                 out = sorted(out, key=sort_func)

/databricks/spark/python/pyspark/rdd.py in sortBy(self, keyfunc, ascending, numPartitions)
    698         [('a', 1), ('b', 2), ('1', 3), ('d', 4), ('2', 5)]
    699         """
--> 700         return self.keyBy(keyfunc).sortByKey(ascending, numPartitions).values()
    701 
    702     def glom(self):

/databricks/spark/python/pyspark/rdd.py in sortByKey(self, ascending, numPartitions, keyfunc)
    666         # the key-space into bins such that the bins have roughly the same
    667         # number of (key, value) pairs falling into them
--> 668         rddSize = self.count()
    669         if not rddSize:
    670             return self  # empty RDD

/databricks/spark/python/pyspark/rdd.py in count(self)
   1094         3
   1095         """
-> 1096         return self.mapPartitions(lambda i: [sum(1 for _ in i)]).sum()
   1097 
   1098     def stats(self):

/databricks/spark/python/pyspark/rdd.py in sum(self)
   1085         6.0
   1086         """
-> 1087         return self.mapPartitions(lambda x: [sum(x)]).fold(0, operator.add)
   1088 
   1089     def count(self):

/databricks/spark/python/pyspark/rdd.py in fold(self, zeroValue, op)
    956         # zeroValue provided to each partition is unique from the one provided
    957         # to the final reduce call
--> 958         vals = self.mapPartitions(func).collect()
    959         return reduce(op, vals, zeroValue)
    960 

/databricks/spark/python/pyspark/rdd.py in collect(self)
    829         # Default path used in OSS Spark / for non-credential passthrough clusters:
    830         with SCCallSiteSync(self.context) as css:
--> 831             sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
    832         return list(_load_from_socket(sock_info, self._jrdd_deserializer))
    833 

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 6 in stage 2.0 failed 4 times, most recent failure: Lost task 6.3 in stage 2.0 (TID 227, 10.139.64.8, executor 0): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/serializers.py", line 181, in _read_with_length
    return self.loads(obj)
  File "/databricks/spark/python/pyspark/serializers.py", line 691, in loads
    return pickle.loads(obj, encoding=encoding)
  File "/databricks/python/lib/python3.7/site-packages/burdock/reader/sql/__init__.py", line 2, in <module>
    from burdock.reader.sql.pandas import PandasReader
  File "/databricks/python/lib/python3.7/site-packages/burdock/reader/sql/pandas.py", line 1, in <module>
    from .sql_base import SqlReader, NameCompare
  File "/databricks/python/lib/python3.7/site-packages/burdock/reader/sql/sql_base.py", line 1, in <module>
    from burdock.reader.base import Reader
  File "/databricks/python/lib/python3.7/site-packages/burdock/reader/base.py", line 1, in <module>
    from .rowset import TypedRowset
  File "/databricks/python/lib/python3.7/site-packages/burdock/reader/rowset.py", line 5, in <module>
    from burdock.metadata.report import Report
  File "/databricks/python/lib/python3.7/site-packages/burdock/metadata/__init__.py", line 1, in <module>
    from .collection import CollectionMetadata
  File "/databricks/python/lib/python3.7/site-packages/burdock/metadata/collection.py", line 3, in <module>
    from burdock.reader.sql.sql_base import NameCompare
ImportError: cannot import name 'NameCompare' from 'burdock.reader.sql.sql_base' (/databricks/python/lib/python3.7/site-packages/burdock/reader/sql/sql_base.py)

**Comment by dylanw-oss** [comment]
@joshua-oss, this blocks it running on Databricks. I workaround it by moving "metadata/report.py" to "output/report.py", is it the right solution?

**Comment by joshua-oss** [comment]
This should fix it:

https://github.com/opendifferentialprivacy/whitenoise-system/pull/152

**Comment by eedeleon** [comment]
Resolved with PR https://github.com/opendifferentialprivacy/whitenoise-system/pull/152
