### ISSUE TITLE
ModuleNotFoundError: No module named 'opendp.whitenoise.sql.parser'

### ISSUE THREAD

**Issue by dylanw-oss** [opendifferentialprivacy/whitenoise-system#161]
import pyspark
from pyspark.sql import SparkSession
from opendp.whitenoise.metadata import CollectionMetadata
from opendp.whitenoise.sql import SparkReader
from opendp.whitenoise.sql import PrivateReader

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<command-3410247141518353> in <module>
      1 import pyspark
      2 from pyspark.sql import SparkSession
----> 3 from opendp.whitenoise.metadata import CollectionMetadata
      4 from opendp.whitenoise.sql import SparkReader
      5 from opendp.whitenoise.sql import PrivateReader

/databricks/python/lib/python3.7/site-packages/opendp/whitenoise/metadata/__init__.py in <module>
----> 1 from .collection import CollectionMetadata
      2 
      3 
      4 __all__ = ["CollectionMetadata"]

/databricks/python/lib/python3.7/site-packages/opendp/whitenoise/metadata/collection.py in <module>
      1 import importlib
      2 import yaml
----> 3 from opendp.whitenoise.sql.reader.sql_base import NameCompare
      4 
      5 # implements spec at https://docs.google.com/document/d/1Q4lUKyEu2W9qQKq6A0dbo0dohgSUxitbdGhX97sUNOM/

/databricks/python/lib/python3.7/site-packages/opendp/whitenoise/sql/__init__.py in <module>
      1 
----> 2 from .private_rewriter import Rewriter
      3 from .private_reader import PrivateReader
      4 from .parse import QueryParser
      5 

/databricks/python/lib/python3.7/site-packages/opendp/whitenoise/sql/private_rewriter.py in <module>
      2 import string
      3 
----> 4 from .parse import QueryParser
      5 from opendp.whitenoise.ast import Validate
      6 

/databricks/python/lib/python3.7/site-packages/opendp/whitenoise/sql/parse.py in <module>
      1 from antlr4 import * #type: ignore
      2 
----> 3 from .parser.SqlSmallLexer import SqlSmallLexer #type: ignore
      4 from .parser.SqlSmallParser import SqlSmallParser #type: ignore
      5 from .parser.SqlSmallVisitor import SqlSmallVisitor #type: ignore

**Comment by eedeleon** [comment]
Thanks for the fix!
