### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by dylanw-oss** [opendifferentialprivacy/whitenoise-system#185]
In Databricks, install whitenoise and execute
from opendp.whitenoise.metadata import CollectionMetadata
meta = CollectionMetadata.from_file('/dbfs/data/PUMS_large.yaml')

got an error message
ModuleNotFoundError: No module named 'yaml'

I have to explicitly install pyyaml.

pyyaml should be included as a requirement in setup.py

**Comment by eedeleon** [comment]
We have updated dependencies and moved import statements to the top of files to catch these errors more quickly
