### ISSUE TITLE
Comments in private_rewriter.py are copied and wrong

### ISSUE THREAD

**Issue by TedTed** [opendifferentialprivacy/whitenoise-system#199]
Hi folks,
First: thanks for open-sourcing this system! This is quite exciting. Please take this bug and the ones that follow as a sign of enthusiastic interest =)
Now, the (small) bug: comments in [this function](https://github.com/opendifferentialprivacy/whitenoise-system/blob/master/sdk/opendp/whitenoise/sql/private_rewriter.py#L45) and the next one seem to be a copy/paste of calculate_avg, and are therefore inaccurate.

**Comment by joshua-oss** [comment]
Thanks for reporting this.  It's fixed in #210
