### ISSUE TITLE
PATECTGAN Student loss has no zero_grad

### ISSUE THREAD

**Issue by Tecnarca** [opendifferentialprivacy/whitenoise-system#280]
In the PATECTGAN class, when the backward step is executed (line 280), its optimizer does not execute the function zero_grad(). Both the CTGAN and PATEGAN implementation did execute this function. 
Why is this not the case here?

**Comment by AprilXiaoyanLiu** [comment]
Thanks Tecnarca. Good catch! It's actually a bug. I'm in the process of fixing it. In the meantime, https://github.com/opendifferentialprivacy/whitenoise-system/pull/283 this is the pull request to fix this issue.

**Comment by Tecnarca** [comment]
Glad i helped!
